"use client";

import React, { useState, useEffect } from 'react';
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { PageHeader } from '@/components/PageHeader';
import { DataStoryBriefing, DataStoryPayload } from '@/components/storytelling/DataStoryBriefing';
import { Database, Sparkles, Search, ArrowRight, Loader2, FileUp, ShieldCheck, CloudDownload, HardDrive } from 'lucide-react';
import { useLocalFileSystem } from '@/lib/data/useLocalFileSystem';
import { MarigoldIcon } from '@/components/MarigoldIcon';
import { useDataConcierge } from '@/hooks/useDataConcierge';

export default function InsightsPage() {
  const [query, setQuery] = useState("");
  const [activeGroup, setActiveGroup] = useState("");
  const { state, publicData, errorMsg, ingestStatus, startQuery, ingestData, reset } = useDataConcierge();

  const [scanStatus, setScanStatus] = useState("");

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setActiveGroup(localStorage.getItem("marigold_active_group") || "");
    }
  }, []);

  const handleQuerySubmit = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!query.trim()) return;

    window.dispatchEvent(new CustomEvent('mari-panel-state-change', { detail: { isOpen: true } }));
    startQuery(query, activeGroup);
  };

  const handleIngest = async (mode: 'permanent' | 'jit') => {
    if (mode === 'permanent') {
      setScanStatus("Performing security scan on public endpoint...");
      setTimeout(() => setScanStatus("HTTPS verified. No malicious payloads detected."), 1500);
      setTimeout(() => setScanStatus("Chunking and streaming directly to local OPFS..."), 3000);
    } else {
      setScanStatus("Streaming data to temporary memory buffer...");
    }
    await ingestData(mode);
    setScanStatus("");
  };

  // The fallback mock payload that represents the ultimate result generated by the LLM
  // (In production, the WASM engine would return this JSON, we are just mocking the final render)
  const mockRenderedStory: DataStoryPayload = {
    id: "final-story",
    headline: "Automated Data Discovery Result",
    plainText: "Mari successfully fetched, processed, and ran SQL against the requested external dataset. We found significant demographic clusters matching your query.",
    verboseText: "Automagic ingestion pipeline executed successfully. Streaming bytes converted to OPFS blocks. WASM index created and queried. Resultant aggregation mapped to Nivo charts.",
    chartData: {
      type: "scatter",
      data: [
        { id: "Group A", data: [{ x: 10, y: 20 }, { x: 30, y: 40 }, { x: 50, y: 60 }] },
        { id: "Group B", data: [{ x: 20, y: 30 }, { x: 40, y: 50 }, { x: 60, y: 70 }] }
      ],
      xAxisLabel: "Variable X",
      yAxisLabel: "Variable Y"
    },
    prompts: [
      { id: "1", text: "Save this analysis", action: "save" },
      { id: "2", text: "Run further regressions on this new data", action: "query" }
    ]
  };

  return (
    <div className="relative h-full overflow-hidden flex flex-col bg-background">
      <div className="px-4 sm:px-6 pt-6 pb-2 z-10 flex-shrink-0">
        <PageHeader
          title="Data Insights & Stories"
          subtitle="Explore visual intelligence briefings generated from your local datasets."
          actions={
            <div className="flex gap-3">
              <a 
                href="/onboarding"
                className="btn-primary"
              >
                <FileUp className="w-4 h-4 mr-2" />
                Open Local .mari File
              </a>
            </div>
          }
        />
      </div>

      <div className="flex-1 overflow-y-auto px-4 sm:px-6 pb-12 flex flex-col">
        {/* Omnibox Section */}
        <div className={`transition-all duration-700 ease-in-out w-full max-w-3xl mx-auto ${(state !== 'IDLE' && state !== 'LOCAL_CHECK') ? 'mt-4 mb-8' : 'mt-[15vh] mb-12'}`}>
          {state === 'IDLE' && (
            <div className="text-center mb-8">
              <div className="w-16 h-16 bg-white border border-border shadow-sm rounded-full flex items-center justify-center text-primary mx-auto mb-6">
                <MarigoldIcon className="w-8 h-8" />
              </div>
              <h2 className="text-3xl font-serif text-text-header mb-3 tracking-tight">What anomalies are you looking for?</h2>
              <p className="text-text-body">Mari will analyze your local data or fetch public data automatically.</p>
            </div>
          )}

          <form onSubmit={handleQuerySubmit} className="relative group">
            <div className={`absolute inset-0 bg-primary/5 rounded-[20px] blur-xl transition-opacity duration-300 ${state !== 'IDLE' ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}`}></div>
            <div className="relative bg-white border-2 border-border focus-within:border-primary shadow-sm rounded-[20px] p-2 flex items-center transition-colors">
              <div className="pl-4 pr-2 text-text-body">
                <Search className="w-6 h-6" />
              </div>
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="e.g., Analyze obesity correlations in public health data..."
                className="flex-1 bg-transparent border-none focus:outline-none text-lg text-text-header placeholder:text-text-body/50 py-3"
                disabled={state !== 'IDLE' && state !== 'RENDERING' && state !== 'ERROR'}
              />
              <Button
                type="submit"
                variant="primary"
                disabled={!query.trim() || (state !== 'IDLE' && state !== 'RENDERING' && state !== 'ERROR')}
                className="ml-2"
                aria-label="Submit search query"
              >
                {(state === 'LOCAL_CHECK') ? <Loader2 className="w-5 h-5 animate-spin" /> : <ArrowRight className="w-5 h-5" />}
              </Button>
            </div>
          </form>
        </div>

        {/* State: LOCAL_CHECK */}
        {state === 'LOCAL_CHECK' && (
          <div className="flex-1 flex flex-col items-center justify-center animate-in fade-in zoom-in-95 duration-500">
            <div className="relative w-24 h-24 mb-8">
              <div className="absolute inset-0 border-4 border-primary/20 rounded-full animate-ping" style={{ animationDuration: '3s' }}></div>
              <div className="absolute inset-0 bg-white border shadow-xl rounded-full flex items-center justify-center z-10">
                <MarigoldIcon className="w-10 h-10 text-primary animate-pulse" />
              </div>
            </div>
            <h3 className="text-xl font-serif text-text-header mb-2">Analyzing Intent...</h3>
            <p className="text-text-body font-mono text-sm max-w-md text-center">Checking local schemas and consulting LLM router.</p>
          </div>
        )}

        {/* State: DATA_DISCOVERY */}
        {state === 'DATA_DISCOVERY' && publicData && (
          <div className="flex-1 animate-in slide-in-from-bottom-8 fade-in duration-700 max-w-2xl mx-auto w-full">
            <Card className="bg-white border-2 border-border shadow-md rounded-[24px] p-8">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-12 rounded-full bg-accent/20 flex items-center justify-center text-accent">
                  <CloudDownload className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-xl font-serif text-text-header">Public Data Required</h3>
                  <p className="text-sm text-text-body">I found an external dataset that matches your query.</p>
                </div>
              </div>
              
              <div className="bg-surface p-4 rounded-xl border border-border-soft mb-8">
                <p className="text-text-body text-sm mb-2"><strong>Mari says:</strong> {publicData.description}</p>
                <div className="flex items-center gap-2 text-xs font-mono text-muted-foreground break-all">
                  <ShieldCheck className="w-4 h-4 shrink-0 text-green-600" />
                  Source: {publicData.source_url}
                </div>
              </div>

              <h4 className="font-bold text-text-header mb-4">How would you like to handle this data?</h4>
              
              <div className="grid gap-4 sm:grid-cols-2">
                <Button 
                  onClick={() => handleIngest('permanent')}
                  variant="secondary"
                  className="h-auto flex-col items-start text-left gap-2 whitespace-normal border-2 hover:border-primary group"
                >
                  <div className="flex items-center gap-2 text-primary font-bold w-full pt-2">
                    <HardDrive className="w-5 h-5" />
                    Save Permanently
                  </div>
                  <p className="text-xs text-text-body pb-2">Download and securely encrypt this data to your local OPFS folder for future use.</p>
                </Button>

                <Button 
                  onClick={() => handleIngest('jit')}
                  variant="secondary"
                  className="h-auto flex-col items-start text-left gap-2 whitespace-normal border-2 hover:border-accent group"
                >
                  <div className="flex items-center gap-2 text-accent font-bold w-full pt-2">
                    <Sparkles className="w-5 h-5" />
                    Single Exploration
                  </div>
                  <p className="text-xs text-text-body pb-2">Stream the data into memory for a JIT (Just-In-Time) analysis. Data is discarded after.</p>
                </Button>
              </div>
            </Card>
          </div>
        )}

        {/* State: INGESTING */}
        {state === 'INGESTING' && (
          <div className="flex-1 flex flex-col items-center justify-center animate-in fade-in zoom-in-95 duration-500">
            <div className="w-16 h-16 bg-white border border-border shadow-sm rounded-full flex items-center justify-center text-primary mx-auto mb-6">
              <Loader2 className="w-8 h-8 animate-spin" />
            </div>
            <h3 className="text-xl font-serif text-text-header mb-2">Automagic Ingestion Active</h3>
            <p className="text-text-body font-mono text-sm max-w-md text-center">{ingestStatus || "Processing stream..."}</p>
          </div>
        )}

        {/* State: ERROR */}
        {state === 'ERROR' && (
          <div className="flex-1 flex flex-col items-center justify-center animate-in fade-in zoom-in-95 duration-500">
            <div className="w-16 h-16 bg-red-100 border border-red-200 shadow-sm rounded-full flex items-center justify-center text-red-600 mx-auto mb-6">
              <ShieldCheck className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-serif text-text-header mb-2">Security Block</h3>
            <p className="text-red-600 font-mono text-sm max-w-md text-center">{errorMsg || "An unknown security error occurred."}</p>
            <Button onClick={reset} variant="outline" className="mt-6">Dismiss & Try Again</Button>
          </div>
        )}

        {/* State: RENDERING */}
        {state === 'RENDERING' && (
          <div className="flex-1 animate-in slide-in-from-bottom-8 fade-in duration-700">
            <DataStoryBriefing story={mockRenderedStory} />
          </div>
        )}
      </div>
    </div>
  );
}
